version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y openjdk-11-jdk
  build:
    commands:
      - echo Compiling the Java application...
      - javac HelloWorld.java
artifacts:
  files:
    - HelloWorld.class
